### ISSUE TITLE
Collaboration with dependo?

### ISSUE THREAD

**Issue by auchenberg** [freizl/js-vd#4]
Just stumbled upon your project, and it looks much similar to a project I did a few years ago, and haven't maintained much since: https://github.com/auchenberg/dependo

Wanna collaborate, maybe consolidate the efforts?

**Comment by freizl** [comment]
actually I tried dependo before I create mine. I simply don't like the animation and D3. :)
it seems more useful to me that being static and support quick navigation.

any thoughts?

**Comment by auchenberg** [comment]
We could merge, and add an option to generate an "interactive" output? Dependo is any close to dead :)

**Comment by freizl** [comment]
are you saying merge some features from Dependo to js-vd? sounds interesting.. what could be?
Maybe create an PR so that we could discuss from there?

**Comment by freizl** [comment]
@auchenberg any further thoughts?

**Comment by freizl** [comment]
close per no further response. (could re-open once more thoughts)
